import { expect, test } from "@playwright/test";
import { loginAs } from "./helpers/auth";
import { admin, getLeague, getLeagueMembers } from "./helpers/db";
import {
  addLeagueMember,
  createExtraUser,
  createLeague,
  loadSeededUsers,
  userId,
} from "./helpers/seed";

/** datetime-local wants `YYYY-MM-DDTHH:mm`. */
function localDateTimeValue(offsetDays = 0): string {
  const d = new Date(Date.now() + offsetDays * 86_400_000);
  return d.toISOString().slice(0, 16);
}

test.describe("leagues: create, join, membership, chat, standings", () => {
  test.beforeAll(async () => {
    await loadSeededUsers();
  });

  test("the leagues index shows an empty state before you join anything", async ({ page }) => {
    // A throwaway user, not a fixture: the fixtures get added to leagues by other
    // specs in this serially-shared database, so "has no leagues" is only
    // reliably true for someone brand new.
    const solo = await createExtraUser("noleagues");
    const { loginAsEmail } = await import("./helpers/auth");
    await loginAsEmail(page, solo.email);
    await page.goto("/leagues");
    await expect(page.getByRole("heading", { name: "Leagues", level: 1 })).toBeVisible();
    await expect(page.getByText("You haven't joined any leagues yet.")).toBeVisible();
  });

  test("creating a league via the UI makes you owner and generates an invite code", async ({
    page,
  }) => {
    await loginAs(page, "owner");
    await page.goto("/leagues");
    await page.getByTestId("create-league-open").click();

    await page.getByTestId("create-league-name").fill("[E2E] UI Created League");
    await page.getByTestId("create-league-buy-in").fill("50");
    await page.getByTestId("create-league-week-start").fill(localDateTimeValue(0));
    await page.getByTestId("create-league-submit").click();

    // Redirects to the new league's page.
    await expect(page).toHaveURL(/\/leagues\/[0-9a-f-]{36}$/);
    const leagueId = page.url().split("/").pop()!;

    const league = await getLeague(leagueId);
    expect(league.name).toBe("[E2E] UI Created League");
    expect(league.buy_in_coins).toBe(50);
    // Auto-generated by the column default.
    expect(league.invite_code).toMatch(/^[A-Z0-9]{6}$/);

    const members = await getLeagueMembers(leagueId);
    expect(members).toHaveLength(1);
    expect(members[0]!.user_id).toBe(userId("owner"));
    expect(members[0]!.role).toBe("owner");

    await expect(page.getByTestId("league-invite-code")).toHaveText(league.invite_code!);
  });

  test("a league cannot be created without a name or a start date", async ({ page }) => {
    await loginAs(page, "owner");
    await page.goto("/leagues");
    await page.getByTestId("create-league-open").click();
    // Both fields are required, so the submit stays disabled.
    await expect(page.getByTestId("create-league-submit")).toBeDisabled();
    await page.getByTestId("create-league-name").fill("[E2E] Nameless");
    await expect(page.getByTestId("create-league-submit")).toBeDisabled();
    await page.getByTestId("create-league-week-start").fill(localDateTimeValue(0));
    await expect(page.getByTestId("create-league-submit")).toBeEnabled();
  });

  test("joining by invite code adds you as a member and bumps the count", async ({ page }) => {
    const { id, inviteCode } = await createLeague({ creator: "owner" });
    expect((await getLeagueMembers(id))).toHaveLength(1);

    await loginAs(page, "alice");
    await page.goto("/leagues");
    await page.getByTestId("join-league-open").click();
    await page.getByTestId("join-league-code").fill(inviteCode.toLowerCase()); // case-insensitive
    await page.getByTestId("join-league-submit").click();

    await expect(page).toHaveURL(new RegExp(`/leagues/${id}$`));

    const members = await getLeagueMembers(id);
    expect(members).toHaveLength(2);
    expect(members.find((m) => m.user_id === userId("alice"))!.role).toBe("member");

    // The index now shows the league with its member count.
    await page.goto("/leagues");
    const card = page.locator(`[data-testid="league-card"][data-league-id="${id}"]`);
    await expect(card).toBeVisible();
    await expect(card).toHaveAttribute("data-member-count", "2");
  });

  test("an invalid invite code is rejected and joins nothing", async ({ page }) => {
    await loginAs(page, "alice");
    await page.goto("/leagues");
    await page.getByTestId("join-league-open").click();
    await page.getByTestId("join-league-code").fill("ZZZZZZ");
    await page.getByTestId("join-league-submit").click();

    await expect(page.getByTestId("join-league-error")).toHaveText(
      "Invalid invite code. Please check and try again."
    );
    await expect(page).toHaveURL(/\/leagues$/);
  });

  test("a full league refuses new members", async ({ page }) => {
    // max_members 2, already holding owner + bob.
    const { id, inviteCode } = await createLeague({
      creator: "owner",
      members: ["bob"],
      maxMembers: 2,
    });
    expect(await getLeagueMembers(id)).toHaveLength(2);

    await loginAs(page, "alice");
    await page.goto("/leagues");
    await page.getByTestId("join-league-open").click();
    await page.getByTestId("join-league-code").fill(inviteCode);
    await page.getByTestId("join-league-submit").click();

    await expect(page.getByTestId("join-league-error")).toHaveText("This league is full.");
    // Nothing was added.
    expect(await getLeagueMembers(id)).toHaveLength(2);
  });

  test("joining a league you are already in just navigates there", async ({ page }) => {
    const { id, inviteCode } = await createLeague({ creator: "owner", members: ["alice"] });

    await loginAs(page, "alice");
    await page.goto("/leagues");
    await page.getByTestId("join-league-open").click();
    await page.getByTestId("join-league-code").fill(inviteCode);
    await page.getByTestId("join-league-submit").click();

    await expect(page).toHaveURL(new RegExp(`/leagues/${id}$`));
    // Still one membership row, not a duplicate.
    expect(
      (await getLeagueMembers(id)).filter((m) => m.user_id === userId("alice"))
    ).toHaveLength(1);
  });

  test("a member cannot forge a membership row for another user", async () => {
    const { id } = await createLeague({ creator: "owner" });
    const { anonClientFor } = await import("./helpers/db");
    const { USERS } = await import("./helpers/fixtures");

    // The INSERT policy is `auth.uid() = user_id` (self-join only).
    const alice = await anonClientFor(USERS.alice.email);
    const { error } = await alice
      .from("league_members")
      .insert({ league_id: id, user_id: userId("bob"), role: "member" });

    expect(error).not.toBeNull();
    expect(await getLeagueMembers(id)).toHaveLength(1);
  });

  test("the league page shows both standings tabs", async ({ page }) => {
    const { id } = await createLeague({ creator: "owner", members: ["alice", "bob"] });
    await loginAs(page, "owner");
    await page.goto(`/leagues/${id}`);

    // "This Week" is the default (tab !== "standings").
    await expect(page.getByTestId("league-tab-weekly")).toHaveAttribute(
      "aria-selected",
      "true"
    );
    await expect(page.getByText("No active week yet")).toBeVisible();

    await page.getByTestId("league-tab-standings").click();
    await expect(page).toHaveURL(/tab=standings/);
    await expect(page.getByTestId("league-tab-standings")).toHaveAttribute(
      "aria-selected",
      "true"
    );
    await expect(page.getByText("Golf scoring — lower points is better")).toBeVisible();
  });

  test("league chat: a member can post, and it reaches another member live", async ({
    browser,
  }) => {
    const { id } = await createLeague({ creator: "owner", members: ["alice"] });

    const ownerContext = await browser.newContext();
    const aliceContext = await browser.newContext();
    try {
      const ownerPage = await ownerContext.newPage();
      const alicePage = await aliceContext.newPage();
      await loginAs(ownerPage, "owner");
      await loginAs(alicePage, "alice");
      await ownerPage.goto(`/leagues/${id}`);
      await alicePage.goto(`/leagues/${id}`);

      await ownerPage.getByTestId("league-chat-input").fill("First message in the league");
      await ownerPage.getByTestId("league-chat-send").click();

      await expect(ownerPage.getByTestId("league-chat-message")).toContainText(
        "First message in the league"
      );

      // Alice's page updates without a reload. This only works because
      // migration 0023 added league_messages to the supabase_realtime
      // publication — before that the subscription never fired.
      await expect(alicePage.getByTestId("league-chat-message")).toContainText(
        "First message in the league",
        { timeout: 20_000 }
      );
    } finally {
      await ownerContext.close();
      await aliceContext.close();
    }
  });

  test("a non-member cannot post to a league's chat", async () => {
    const { id } = await createLeague({ creator: "owner" });
    const { anonClientFor } = await import("./helpers/db");
    const { USERS } = await import("./helpers/fixtures");

    // The INSERT policy requires membership as well as self-authorship.
    const alice = await anonClientFor(USERS.alice.email);
    const { error } = await alice
      .from("league_messages")
      .insert({ league_id: id, user_id: userId("alice"), body: "let me in" });

    expect(error).not.toBeNull();
    const { data } = await admin.from("league_messages").select("id").eq("league_id", id);
    expect(data ?? []).toHaveLength(0);
  });

  test("a non-member cannot read a private league's chat", async () => {
    const { id } = await createLeague({ creator: "owner" });
    await admin
      .from("league_messages")
      .insert({ league_id: id, user_id: userId("owner"), body: "members only" });

    const { anonClientFor } = await import("./helpers/db");
    const { USERS } = await import("./helpers/fixtures");
    const alice = await anonClientFor(USERS.alice.email);

    // RLS filters rather than errors, so the proof is an empty result even when
    // asking for this league's messages by id directly.
    const { data, error } = await alice
      .from("league_messages")
      .select("*")
      .eq("league_id", id);
    expect(error).toBeNull();
    expect(data).toEqual([]);
  });

  test("a large league renders every member in the all-time standings", async ({ page }) => {
    const { id } = await createLeague({ creator: "owner", members: ["alice", "bob"] });
    const extra = await createExtraUser("league1");
    await addLeagueMember(id, extra.id);

    await loginAs(page, "owner");
    await page.goto(`/leagues/${id}?tab=standings`);
    await expect(page.getByTestId("alltime-standings-row")).toHaveCount(4);
  });

  test.fixme(
    "a member can leave a league",
    async () => {
      // not built yet — there is no leave-league control anywhere in the UI, and
      // no server action for it. The RLS DELETE policy on league_members already
      // permits self-removal, so this is presentation work only.
    }
  );

  test.fixme(
    "an owner can rename a league or change its buy-in",
    async () => {
      // not built yet — no league settings UI or mutation exists.
    }
  );
});
